/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/body.glb')
  return (
    <group {...props} dispose={null}>
      <spotLight intensity={125.26} angle={1.48} penumbra={0.39} decay={2} position={[2.86, -0.34, 4.92]} rotation={[-0.22, 0.47, 0.17]} />
      <spotLight intensity={59.73} angle={0.79} penumbra={0.39} decay={2} position={[-2.82, 0.22, -4.63]} rotation={[-3.03, -0.37, -2.81]} />
      <mesh geometry={nodes.head.geometry} material={nodes.head.material} position={[0.02, 1.05, 0.23]} rotation={[-0.2, 0, 0]} scale={[0.75, 0.86, 0.7]} />
      <mesh geometry={nodes.body.geometry} material={nodes.body.material} position={[-0.22, -0.05, 0]} rotation={[-0.01, 0.02, 0.14]} scale={[0.92, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/body.glb')
