# Generated by Django 3.1.3 on 2022-12-13 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='disease name', max_length=200)),
                ('tname', models.CharField(default='நோய் பெயர்', max_length=200)),
                ('symptoms', models.CharField(default='symp', max_length=1000)),
                ('casuedby', models.CharField(default='causes', max_length=100)),
                ('severity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('doctorneed', models.BooleanField(default=False)),
                ('cure', models.CharField(default='cures', max_length=1000)),
                ('todo', models.CharField(default='todo', max_length=2000)),
                ('suggestmedication', models.BooleanField(default=False)),
                ('medication', models.CharField(default='medication', max_length=1000)),
            ],
        ),
    ]
