# Generated by Django 3.1.3 on 2022-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='bedrestrequirement',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='bedrestrequirementdays',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes',
            field=models.CharField(default='tiredness', max_length=1000),
        ),
        migrations.AddField(
            model_name='disease',
            name='partsattacked',
            field=models.CharField(default='head,leg,body,hand,neck', max_length=1000),
        ),
    ]
