# Generated by Django 4.1.3 on 2022-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20221213_2305"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="about",
            field=models.TextField(default="about", max_length=1000),
        ),
    ]
