# Generated by Django 4.1.3 on 2022-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_disease_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="casuedby",
            field=models.TextField(default="causes", max_length=1000),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms",
            field=models.TextField(default="symp", max_length=1000),
        ),
    ]
