# Generated by Django 3.1.3 on 2022-12-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelnames', models.CharField(default='general', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(default='medicine name', max_length=1000)),
                ('nednamet', models.CharField(default='மருந்து பெயர்', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(default='general', max_length=10000),
        ),
        migrations.AddField(
            model_name='news',
            name='newslabel',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
